# Generated by Django 5.1.6 on 2025-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта клиента')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий о клиенте')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name', 'email'],
            },
        ),
    ]
