# Generated by Django 5.1.6 on 2025-02-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('emailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первой отправки')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('started', 'Запущена')], default='created', max_length=15, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailings.message', verbose_name='Сообщение')),
                ('recipients', models.ManyToManyField(to='clients.clients', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['end_datetime'],
            },
        ),
    ]
