# Generated by Django 5.1.6 on 2025-02-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailings', '0002_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_attempt', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('status_ok', 'Успешно'), ('status_nok', 'Не успешно')], max_length=15, verbose_name='Статус')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='emailings.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['datetime_attempt', 'status'],
            },
        ),
    ]
