# Generated by Django 5.1.6 on 2025-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailings', '0004_mailing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='all_sent_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='successful_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='unsuccessful_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
