# Generated by Django 5.1.6 on 2025-02-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailings', '0005_mailing_all_sent_messages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['end_datetime'], 'permissions': [('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
